---
title: Miya Corner
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: inisial M
email: miya@teknik.io
description: 'Limited by Imagination

'
baseurl: ''
url: http://miyaku.github.io
permalink: "/:categories/:title.M"
twitter_username: mifansindonesia
github_username: mifansindonesia
markdown: kramdown
