title: "ℳ"
description: > # this means to ignore newlines until "baseurl:"
  Limited by Imagination
baseurl: ""
url: "https://sabyan.github.io/"
permalink: "/:categories/:title.M"
repository: Sabyan/sabyan
paginate: 5
github_profile: "https://github.com/Miyaku"
user: "ℳιуα"
user_email: "miyaku@yandex.com"
#google_tracking_id: "UA-"
#google_site_verification: "UA-"
disqus_shortname: "miyaku"
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true